# config template for the roq-binance-futures gateway

symbols = [
  "^BTCUSD[A-Z]?(_[0-9]{6})?$",
  "^ETHUSD[A-Z]?(_[0-9]{6})?$"
]

[accounts]

  [accounts.A1]
  master = true
  login = "YOUR_BINANCE_FUTURES_API_KEY_GOES_HERE"
  secret = "YOUR_BINANCE_FUTURES_SECRET_GOES_HERE"
  symbols = [ ".*" ]

[users]

  [users.test]
  password = "1234"
  symbols = ".*"

  [users.trader]
  password = "secret"
  accounts = [ "A1" ]
  symbols = [ ".*BTC.*", ".*ETH.*" ]

[rate_limits]

  [rate_limits.global]
    type = "ORDER_ACTION"
    aggregate = true
    request_limit = 100
    monitor_period = "10s"
    ban_period = "5m"
